config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'event#index'
  resources :event do
    resources :charges, only: %i[new create]
    resources :attendances, only: %i[index]
  end
  resources :user, only: %i[show edit update]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  private

  def event_participation_send
    UserMailer.event_participation_email(User.find(user_id), Event.find(event_id)).deliver_now
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :start_date, presence: true
  validate :past?
  validates :duration, presence: true
  validate :duration_valid?
  validates :title, presence: true, length: { minimum: 5, maximum: 140 }
  validates :description, presence: true, length: { minimum: 20, maximum: 1000 }
  validates :price, presence: true, inclusion: { in: 0..1000 }
  validates :location, presence: true
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances

  def self.new_event(params)
    Event.new(
      start_date: params[:start_date],
      duration: params[:duration],
      title: params[:title],
      description: params[:description],
      price: params[:price],
      location: params[:location]
    )
  end

  def self.update_event(event, params)
    event.update(
      title: params[:title],
      start_date: params[:start_date],
      duration: params[:duration],
      location: params[:location],
      price: params[:price],
      description: params[:description]
    )
  end

  private

  def duration_valid?
    errors.add(:duration, 'la durée doit etre positive et incrémentée de 5 en 5') unless
      duration.positive? && (duration % 5).zero?
  end

  def past?
    return false if start_date.nil?

    errors.add(:start_date, 'la date ne doit pas etre dans le passé') unless
      start_date > Time.zone.now
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances

  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  def index
    @attendees = []
    Attendance.where(event_id: params[:event_id]).each do |attendee|
      @attendees << User.find(attendee.user_id)
    end
  end
end

app/controllers/charges_controller.rb
# frozen_string_literal: true

class ChargesController < ApplicationController
  include ChargesHelper

  def new
    free?(Event.find(params[:event_id]))
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    begin
      Checkout.new(@event.price, params)
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_charge_path(event_id: event.id)
    end
    Attendance.create(event: @event, user: current_user)
  end
end

app/controllers/event_controller.rb
# frozen_string_literal: true

class EventController < ApplicationController
  include EventHelper

  before_action :can_enter?, only: %i[new create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @user = User.find(Attendance.find_by(event: @event, creator: true).user_id)
    @attendances = Attendance.where(event: @event)
  end

  def new; end

  def create
    event = Event.new_event(params)
    if event.save
      Attendance.create(event: event, user: current_user, creator: true)
      redirect_to event_path(event.id), notice: 'évenement crée avec succés'
    else
      flash.now[:alert] = "Erreur lors de la creation de l'event, veuillez verifier le formulaire"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if Event.update_event(@event, params)
      redirect_to event_path(params[:id]), notice: 'event modifié'
    else
      flash.now[:alert] = 'Erreur, veuillez verifier le formulaire'
      render :edit
    end
  end

  def destroy
    Event.find(params[:id]).destroy
    redirect_to root_path, notice: 'event supprimé'
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  include UserHelper

  before_action :can_enter?

  def show
    @user = User.find(params[:id])
    @events = []
    Attendance.where(user: @user, creator: true).each do |event|
      @events << Event.find(event.event_id)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    User.find(params[:id]).update(
      first_name: params[:first_name],
      last_name: params[:last_name],
      description: params[:description]
    )
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
end

app/helpers/charges_helper.rb
# frozen_string_literal: true

module ChargesHelper
  def free?(event)
    return unless event.price.zero?

    Attendance.create(event: event, user: current_user)
    redirect_to event_path(params[:event_id]), notice: 'participation prise en compte'
  end
end

app/helpers/event_helper.rb
# frozen_string_literal: true

module EventHelper
  def can_enter?
    redirect_to new_user_session_path, alert: 'veuillez vous connecter' unless user_signed_in?
  end

  def creator?
    attendance = Attendance.find_by(user: current_user, event_id: params[:id])
    return false unless user_signed_in?
    return false if attendance.nil?

    attendance.creator
  end

  def participating?
    true unless Attendance.find_by(user: current_user, event_id: params[:id]).nil?
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def can_enter?
    redirect_to new_user_session_path, alert: 'veuillez vous connecter' if user_signed_in? == false
    return if current_user.id == params[:id].to_i

    redirect_to root_path, alert: 'veuillez vous connecter avec le bon compte utilisateur'
  end
end

app/views/attendances/index.html.erb
<% @attendees.each do |attendee| %>
  <%= attendee.first_name %>
  <%= attendee.last_name %>
  <%= attendee.email %>
<% end %>
<%= link_to "modifier l'evenement", edit_event_path(params[:event_id]) %>

app/views/charges/create.html.erb
<h2>Merci, vous avez payé <strong>$<%= @event.price %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag event_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>

    <label class="amount">
      <span>Prix : <%= @event.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= (@event.price * 100).to_i %>>"
          data-locale="auto">
  </script>
<% end %>

app/views/event/edit.html.erb
<%= form_tag(url_for(action: 'update'), method: 'put') %>
<%= label_tag 'Titre' %>
<%= text_field_tag 'title', @event.title %>
<%= label_tag 'Date de début' %>
<%= date_field_tag 'start_date', @event.start_date %>
<%= label_tag 'Durée' %>
<%= number_field_tag 'duration', @event.duration %>
<%= label_tag 'Lieux' %>
<%= text_field_tag 'location', @event.location %>
<%= label_tag 'Prix' %>
<%= text_field_tag 'price', @event.price %>
<%= label_tag 'Description' %>
<%= text_field_tag 'description', @event.description %>
<%= submit_tag('modifier') %>
<%= link_to 'supprimer', event_path, method: :delete, data: {:confirm => 'Voulez vous vraiment supprimer ce gossip ?'} %>

app/views/event/index.html.erb
<div class='row my-3'>
  <% @events.each do |event| %>
    <div class="col-sm-4 my-3">
      <div class="card bg-dark text-white">
        <img src="https://img.20mn.fr/sIChN5W-TCG0VWSpGYJYLw/768x492_tous-trolls.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class='card-title'><%= event.title %></h5>
          <p class='card-text'><%= event.start_date %></p>
          <p class='card-text'><%= event.description %></p>
          <p class='card-text text-muted'><%= event.price %> $</p>
          <%= link_to 'Voir', event_path(event.id), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/event/new.html.erb
<%= form_tag(url_for(action: 'create'), method: 'post', class: 'form-group') %>
<%= label_tag 'Titre' %>
<%= text_field_tag 'title', nil, class: '', placeholder: 'titre'%>
<%= label_tag 'Date De Debut' %>
<%= date_field_tag 'start_date', nil, class: ''%>
<%= label_tag 'Durée' %>
<%= number_field_tag 'duration', nil, class: '', placeholder: '60'%>
<%= label_tag 'prix' %>
<%= number_field_tag 'price', nil, class: '', placeholder: '15'%>
<%= label_tag 'Lieux' %>
<%= text_field_tag 'location', nil, class: '', placeholder: 'paris, zenith'%>
<%= label_tag 'Description' %>
<%= text_area_tag 'description', nil, class: '', placeholder: '...'%>
<%= submit_tag('Créer', class: '') %>

app/views/event/show.html.erb
<%= @event.title %>
<%= @event.description %>
<%= @event.start_date %>
<%= @event.location %>
<%= @event.price %>
<%= @attendances.count %>
<br/>
<!-- TODO: afficher le lien de participation uniquement au users qui ne particie pas encore a l'event, sinon afficher
 une phrase style vous participez deja -->
<%= link_to 'participer' , new_event_charge_path(event_id: @event.id) %>
<% if creator? %>
  <%= link_to 'voir la liste des invités', event_attendances_path(event_id: params[:id]) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eventbrite</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <!-- iconify -->
  <script src="https://code.iconify.design/2/2.0.4/iconify.min.js"></script>
</head>

<body class='bg-dark text-white'>
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-dark">
  <div class="container-fluid">
    <%= link_to "Eventbrite", root_path, class: 'navbar-brand text-white' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Accueil", root_path, class: 'nav-link text-white' %>
        </li>
        <li class="nav-item">
          <%= link_to "Créer un évenement", new_event_path, class: 'nav-link text-white' %>
        </li>
      </ul>
    </div>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-muted" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="iconify" data-icon="mdi:account"></span>
      </a>
      <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Déconnection", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
          </li>
          <li>
            <%= link_to "Modifier email", edit_user_registration_path, class: 'nav-link text-white' %>
          </li>
          <li>
            <%= link_to 'Mes évenements', user_path(current_user.id), class: 'nav-link text-white' %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign in", new_user_session_path, class: 'nav-link text-white' %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>
          </li>
        <% end %>
      </ul>
    </li>
  </div>
</nav>
<div class='container my-5'>
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <span class="iconify mb-1 mr-3" data-icon="mdi:alert-circle-outline"></span>
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
          </div>
        <% elsif type == 'notice' %>
          <div class="alert alert-success alert-dismissible fade show" role="alert">
            <span class="iconify mb-1 mr-3" data-icon="mdi:alert-circle-outline"></span>
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
          </div>
        <% else %>
          <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <span class="iconify mb-1 mr-3" data-icon="mdi:alert-circle-outline"></span>
            <%= msg %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
            </button>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/user/edit.html.erb
<div class="row justify-content-center">
  <div class="card bg-dark border border-dark p-5">
    <h3 class="border-bottom pb-3 mb-3">Modifier profil</h3>
    <%= form_tag(url_for(action: 'update'), method: 'put', class: 'form-group') do %>
      <div class="row">
        <div class="col">
          <%= label_tag 'Prenom' %>
          <div class="input-group mb-3">
              <span class="input-group-text border-secondary bg-dark text-white">
                <span class="iconify" data-icon="mdi:account-circle-outline"></span>
              </span>
            <%= text_field_tag 'first_name', @user.first_name, class: 'form-control border-secondary bg-dark text-white', placeholder: 'francis' %>
          </div>
        </div>
        <div class="col">
          <%= label_tag 'Nom' %>
          <div class="input-group mb-3">
              <span class="input-group-text border-secondary bg-dark text-white">
                <span class="iconify" data-icon="mdi:account-circle-outline"></span>
              </span>
            <%= text_field_tag 'last_name', @user.last_name, class: 'form-control border-secondary bg-dark text-white', placeholder: 'cabrel' %>
          </div>
        </div>
        <div class="col">
          <%= label_tag 'description' %>
          <div class="input-group mb-3">
              <span class="input-group-text border-secondary bg-dark text-white">
                <span class="iconify" data-icon="mdi:table-of-contents"></span>
              </span>
            <%= text_area_tag 'description', @user.description, class: 'form-control bg-dark text-white border-secondary hover-shadow', placeholder: 'decrit toi en moins de 140 characteres', rows: "8", style: "height:100%;" %>
          </div>
        </div>
      </div>
      <%= submit_tag('Modifier', class: 'btn btn-secondary mt-3') %>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="row my-3">
  <div class="col text-left ml-5">
    <h3 class="">
      <span class="iconify mb-1" data-icon="mdi:account-circle-outline"></span>
      <%= @user.first_name %> <%= @user.last_name %>
    </h3>
    <p><%= @user.description %></p>
  </div>
  <div class="col-sm-4 text-left ml-5">
    <p>
      <span class="iconify mb-1 text-secondary" data-icon="mdi:email-outline"></span>
      <%= @user.email %>
    </p>
  </div>
  <div class="col-sm-2 text-left">
    <%= link_to 'modifier compte', edit_user_registration_path, class: 'nav-link text-white' %>
    <%= link_to 'modifier profil', edit_user_path, class: 'nav-link text-white' %>
  </div>
</div>
<div class='row my-3'>
  <% @events.each do |event| %>
    <div class="col-sm-4 my-3">
      <div class="card bg-dark text-white">
        <img src="https://img.20mn.fr/sIChN5W-TCG0VWSpGYJYLw/768x492_tous-trolls.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class='card-title'><%= event.title %></h5>
          <p class='card-text'><%= event.start_date %></p>
          <p class='card-text'><%= event.description %></p>
          <p class='card-text text-muted'><%= event.price %> $</p>
          <%= link_to 'Voir', event_path(event.id), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>